apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-os-server
  namespace: unifi
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "unifi.crust.life"
    secretName: tls-secret
  rules:
  - host: unifi.crust.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi-os-server-webui-svc
            port:
              number: 443
