apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
      hostNetwork: false
      replicaCount: 1
      strategy:
        type: Recreate
      tcp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-tcp"
      udp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-udp"
      extraPorts:
        - name: rtp-tcp
          containerPort: 5005
          protocol: TCP
        - name: id-hub-tcp
          containerPort: 9543
          protocol: TCP
        - name: speedtest-tcp
          containerPort: 6789
          protocol: TCP
        - name: comm-tcp
          containerPort: 8080
          protocol: TCP
        - name: network-app-tcp
          containerPort: 8443
          protocol: TCP
        - name: hotspot-sec-tcp
          containerPort: 8444
          protocol: TCP
        - name: site-sup-tcp
          containerPort: 11084
          protocol: TCP
        - name: aqmps-tcp
          containerPort: 5671
          protocol: TCP
        - name: redirect-0-tcp
          containerPort: 8880
          protocol: TCP
        - name: redirect-1-tcp
          containerPort: 8881
          protocol: TCP
        - name: redirect-2-tcp
          containerPort: 8882
          protocol: TCP
        - name: stun-udp
          containerPort: 3478
          protocol: UDP
        - name: syslog-udp
          containerPort: 5514
          protocol: UDP
        - name: discovery-udp
          containerPort: 10003
          protocol: UDP
      service:
        enabled: true
        type: LoadBalancer
        extraPorts:
          - name: unifi-rtp
            port: 5005
            targetPort: 5005
            protocol: TCP
          - name: unifi-id-hub
            port: 9543
            targetPort: 9543
            protocol: TCP
          - name: unifi-speedtest
            port: 6789
            targetPort: 6789
            protocol: TCP
          - name: unifi-comm
            port: 8080
            targetPort: 8080
            protocol: TCP
          - name: unifi-network-app
            port: 8443
            targetPort: 8443
            protocol: TCP
          - name: unifi-hotspot-sec
            port: 8444
            targetPort: 8444
            protocol: TCP
          - name: unifi-site-sup
            port: 11084
            targetPort: 11084
            protocol: TCP
          - name: unifi-aqmps
            port: 5671
            targetPort: 5671
            protocol: TCP
          - name: unifi-redirect-0
            port: 8880
            targetPort: 8880
            protocol: TCP
          - name: unifi-redirect-1
            port: 8881
            targetPort: 8881
            protocol: TCP
          - name: unifi-redirect-2
            port: 8882
            targetPort: 8882
            protocol: TCP
          - name: unifi-stun
            port: 3478
            targetPort: 3478
            protocol: UDP
          - name: unifi-syslog
            port: 5514
            targetPort: 5514
            protocol: UDP
          - name: unifi-discovery
            port: 10003
            targetPort: 10003
            protocol: UDP
