apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    strategy:
      type: Recreate
    controller:
      hostNetwork: false
      kind: Deployment
      replicaCount: 1
      service:
        enabled: true
        type: LoadBalancer
        extraPorts:
          - name: "unifi-os-server-rtp-svc"
            port: 5005
            targetPort: 5005
            protocol: TCP
          - name: "unifi-os-server-id-hub-svc"
            port: 9543
            targetPort: 9543
            protocol: TCP
          - name: "unifi-os-server-mobile-speedtest-svc"
            port: 6789
            targetPort: 6789
            protocol: TCP
          - name: "unifi-os-server-communication-svc"
            port: 8080
            targetPort: 8080
            protocol: TCP
          - name: "unifi-os-server-network-app-svc"
            port: 8443
            targetPort: 8443
            protocol: TCP
          - name: "unifi-os-server-hotspot-secured-svc"
            port: 8444
            targetPort: 8444
            protocol: TCP
          - name: "unifi-os-server-site-supervisor-svc"
            port: 11084
            targetPort: 11084
            protocol: TCP
          - name: "unifi-os-server-aqmps-svc"
            port: 5671
            targetPort: 5671
            protocol: TCP
          - name: "unifi-os-server-hotspot-redirect-0-svc"
            port: 8880
            targetPort: 8880
            protocol: TCP
          - name: "unifi-os-server-hotspot-redirect-1-svc"
            port: 8881
            targetPort: 8881
            protocol: TCP
          - name: "unifi-os-server-hotspot-redirect-2-svc"
            port: 8882
            targetPort: 8882
            protocol: TCP
          - name: "unifi-os-server-stun-svc"
            port: 3478
            targetPort: 3478
            protocol: UDP
          - name: "unifi-os-server-syslog-svc"
            port: 5514
            targetPort: 5514
            protocol: UDP
          - name: "unifi-os-server-discovery-svc"
            port: 10003
            targetPort: 10003
            protocol: UDP
