apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
      hostNetwork: false
      replicaCount: 1
      strategy:
        type: Recreate
      tcp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-tcp"
      udp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-udp"
      service:
        enabled: true
        type: LoadBalancer
