apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
      hostNetwork: false
      replicaCount: 1
      strategy:
        type: Recreate
      tcp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-tcp"
      udp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-udp"
      service:
        enabled: true
        type: LoadBalancer
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: unifi-os-server-rtp-svc
      port: 5005
      protocol: TCP
      targetPort: 5005
    - name: unifi-os-server-aqmps
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: unifi-os-server-mobile-speedtest-svc
      port: 6789
      protocol: TCP
      targetPort: 6789
    - name: unifi-os-server-communication-svc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: unifi-os-server-network-app-svc
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: unifi-os-server-hotspot-secured-svc
      port: 8444
      protocol: TCP
      targetPort: 8444
    - name: unifi-os-server-hotspot-redirect-0-svc
      port: 8880
      protocol: TCP
      targetPort: 8880
    - name: unifi-os-server-hotspot-redirect-1-svc
      port: 8881
      protocol: TCP
      targetPort: 8881
    - name: unifi-os-server-hotspot-redirect-2-svc
      port: 8882
      protocol: TCP
      targetPort: 8882
    - name: unifi-os-server-id-hub-svc
      port: 9543
      protocol: TCP
      targetPort: 9543
    - name: unifi-os-server-site-supervisor-svc
      port: 11084
      protocol: TCP
      targetPort: 11084
    - name: unifi-os-server-stun-svc
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: unifi-os-server-syslog-svc
      port: 5514
      protocol: UDP
      targetPort: 5514
    - name: unifi-os-server-discovery-svc
      port: 10003
      protocol: UDP
      targetPort: 10003
