apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
      hostNetwork: false
      replicaCount: 1
      strategy:
        type: Recreate
      tcp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-tcp"
      udp:
        configMapNamespace: "kube-system"
        configMapName: "ingress-nginx-udp"
      service:
        enabled: true
        type: LoadBalancer
      customPorts:
        - name: unifi-os-server-rtp-svc
          containerPort: 5005
          protocol: TCP
        - name: unifi-os-server-id-hub-svc
          containerPort: 9543
          protocol: TCP
        - name: unifi-os-server-mobile-speedtest-svc
          containerPort: 6789
          protocol: TCP
        - name: unifi-os-server-communication-svcc
          containerPort: 8080
          protocol: TCP
        - name: unifi-os-server-network-app-svc
          containerPort: 8443
          protocol: TCP
        - name: unifi-os-server-hotspot-secured-svc
          containerPort: 8444
          protocol: TCP
        - name: unifi-os-server-site-supervisor-svc
          containerPort: 11084
          protocol: TCP
        - name: unifi-os-server-aqmps-svc
          containerPort: 5671
          protocol: TCP
        - name: unifi-os-server-hotspot-redirect-0-svc
          containerPort: 8880
          protocol: TCP
        - name: unifi-os-server-hotspot-redirect-1-svc
          containerPort: 8881
          protocol: TCP
        - name: unifi-os-server-hotspot-redirect-2-svc
          containerPort: 8882
          protocol: TCP
        - name: unifi-os-server-stun-svc
          containerPort: 3478
          protocol: UDP
        - name: unifi-os-server-syslog-svc
          containerPort: 5514
          protocol: UDP
        - name: unifi-os-server-discovery-svc
          containerPort: 10003
          protocol: UDP
